services:
  - type: web
    name: background-removal-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        sync: false
